### ISSUE TITLE
jsonb as column type throws an error message

### ISSUE THREAD

**Issue by cioa00** [kaiko/zazler#6]
```
Warning: no DbConnPg.type 3802
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at types.t.map (/var/node/zv1033/node_modules/zazler/db.js:122:45)
    at Array.map (<anonymous>)
    at Object.runQ (/var/node/zv1033/node_modules/zazler/db.js:122:41)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
Seems that JSONB type is not supported at the moment

**Comment by cioa00** [comment]
In meantime i got more information related with types. It seems i can define missing types by myself, like 
```
api.conn.pg.types.setTypeParser(3802, 'text', v => JSON.parse(v));
```
