### ISSUE TITLE
Version 1.0.53 installation failed (node 8.11.4)

### ISSUE THREAD

**Issue by cioa00** [kaiko/zazler#7]
```
(test.vps) | branch: /var/node/test1053 default | root@clone:/var/node/test1053# npm install /home/testhome/zazler-1.0.53.tgz

> ibm_db@2.4.0 install /var/node/test1053/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz...

100.00% | 21040638 bytes downloaded out of 21040638 bytes.

****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in undefined   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************

Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...

make: Entering directory `/var/node/test1053/node_modules/ibm_db/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
make: Leaving directory `/var/node/test1053/node_modules/ibm_db/build'

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
make: g++: Command not found
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 127
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "/root/.nvm/versions/node/v8.11.4/bin/node" "/root/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/var/node/test1053/node_modules/ibm_db/installer/clidriver"
gyp ERR! cwd /var/node/test1053/node_modules/ibm_db
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"' }
npm WARN enoent ENOENT: no such file or directory, open '/var/node/test1053/package.json'
npm WARN test1053 No description
npm WARN test1053 No repository field.
npm WARN test1053 No README data
npm WARN test1053 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.4.0 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@2.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-10T05_20_33_653Z-debug.log
```

**Comment by tiitremmel** [comment]
@cioa00  quick workaround would be ``curl -O `npm v zazler dist.tarball` ``, extract it and remove `ibm_db` and `oracledb` from `package.json` dependencies object. then `npm pack` and try to install result tarball version

**Comment by cioa00** [comment]
That way it works just fine. Thank you.

**Comment by tiitremmel** [comment]
@kaiko You can close this issue
